pipeline {
    agent any
    /* {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    } */
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                // sh './jenkins/scripts/deliver.sh'
                sh 'curl -T "target/mvnwebapp.war" "http://deployer:password@localhost:8081/manager/text/deploy?path=/WebApp&update=true&tag=${${BUILD_TAG}// /_}" --ipv4'
                echo 'Success!'
            }
        }
    }
}
